---
- name: Deploy App
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    deployment_date: "{{ ansible_date_time.date }}"
    deployment_id: "{{ lookup('env', 'GITHUB_RUN_ID') | default(ansible_date_time.epoch) }}"
    project_dir: "/tmp/deploy/{{ deployment_date }}/bntd/{{ deployment_id }}"

  tasks:
    - name: Create deployment directory
      file:
        path: "{{ project_dir }}"
        state: directory
        mode: '0755'

    - name: Sync code to deployment directory
      synchronize:
        src: "{{ playbook_dir }}/"
        dest: "{{ project_dir }}"
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=venv"
          - "--exclude=__pycache__"

    - name: Ensure the virtualenv package is installed (Debian/Ubuntu)
      apt:
        name: python3-virtualenv
        state: present
      become: yes

    - name: Create venv (using virtualenv)
      command: virtualenv venv
      args:
        chdir: "{{ project_dir }}"
        creates: "{{ project_dir }}/venv/bin/activate"

    - name: Install Python dependencies
      pip:
        requirements: "{{ project_dir }}/requirements.txt"
        virtualenv: "{{ project_dir }}/venv"
        # Tells Ansible to use the `virtualenv` command
        virtualenv_command: "virtualenv"
        state: present

    - name: Copy uvicorn service file
      template:
        src: uvicorn.service.j2
        dest: /etc/systemd/system/uvicorn.service
        mode: "0644"
      become: yes

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes
      become: yes
    - name: Start and enable uvicorn service
      systemd:
        name: uvicorn
        state: restarted
        enabled: yes
      become: yes


    - name: Wait for Uvicorn to be up
      wait_for:
        host: 127.0.0.1
        port: 8000
        timeout: 30

    - name: Check health endpoint
      uri:
        url: http://127.0.0.1:8000
        return_content: yes
      register: health_check
      retries: 3
      delay: 5
      until: health_check.status == 200

