name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.39.0

      - name: Check formatting
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Run tests
        run: deno test

  deploy-staging:
    needs: lint-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.39.0

      # You'll need to configure deployment secrets in your repository settings
      - name: Deploy to staging
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          # Add your deployment commands here
          echo "Deploying to staging environment..."
          # Example: deno run --allow-net --allow-env deploy.ts staging