name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.39.0

      - name: Check formatting
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Start server and run tests
        run: |
          deno run --allow-net main.ts &
          sleep 2  # Wait for server to start
          deno test --allow-net
          kill %1  # Stop the server

