name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2

      - name: Install Docker
        uses: docker/setup-buildx-action@v3

      - name: Install Nitric CLI
        run: curl -L https://nitric.io/install | bash

      - name: Add Nitric to PATH
        run: echo "$HOME/.nitric/bin" >> $GITHUB_PATH

      - name: Check formatting
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Start Nitric and run tests
        run: |
          # Start Nitric in the background
          nitric start &

          # Wait for Nitric to be ready (adjust timeout as needed)
          timeout 30 bash -c 'until curl -s http://localhost:4001 > /dev/null; do sleep 1; done'

          # Run tests
          deno test --allow-net --allow-env

          # Stop Nitric
          kill %1
