name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2

      - name: Install Docker
        uses: docker/setup-buildx-action@v3

      - name: Check formatting
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Run tests
        run: deno test --allow-env --allow-read --allow-sys --allow-net
