name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Start application
      run: |
        pkill -f "uvicorn app.main:app" || true
        nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 &
